=== Imejpul/lm-xml-dtds/02_ejercicios/02_agenda/agenda.dtd
<!ELEMENT agenda (contacto*)>

<!ELEMENT contacto (nombre, direccion, ciudad, provincia, cp, numeros, email, web, companya)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

<!ELEMENT numeros (telefono, fax)>

    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT fax (#PCDATA)>

<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT companya (#PCDATA)>

=== Imejpul/lm-xml-dtds/02_ejercicios/02_agenda/agenda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacto>
        <nombre>ivan</nombre>
        <direccion>el alto de armentia</direccion>
        <ciudad>arrigorriagalabeitia</ciudad>
        <provincia>cundinamarca</provincia>
        <cp>00000</cp>
        <numeros>
            <telefono>676767676</telefono>
            <fax></fax>
        </numeros>
        <email>123@123.com</email>
        <web>www.123.com</web>
        <companya>laxula</companya>
    </contacto>
</agenda>
