=== Imejpul/lm-xml-dtds/02_ejercicios/07_futbol/resultados_v1.dtd
<!ELEMENT resultados (partido+)>

    <!ELEMENT partido (local, visitante, resultado)>

        <!ELEMENT local (#PCDATA)>

        <!ELEMENT visitante (#PCDATA)>

        <!ELEMENT resultado (goles_local, goles_visitante)>
            <!ELEMENT goles_local (#PCDATA)>
            <!ELEMENT goles_visitante (#PCDATA)>

=== Imejpul/lm-xml-dtds/02_ejercicios/07_futbol/resultados_v1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE resultados SYSTEM "resultados_v1.dtd">
<resultados>
    <partido>
        <local>Zaragoza</local>
        <visitante>Villarreal</visitante>
        <resultado>
            <goles_local>2</goles_local>
            <goles_visitante>1</goles_visitante>
        </resultado>
    </partido>
    <partido>
        <local>Athletic</local>
        <visitante>Real Sociedad</visitante>
        <resultado>
            <goles_local>2</goles_local>
            <goles_visitante>0</goles_visitante>
        </resultado>
    </partido>
    <partido>
        <local>Rayo</local>
        <visitante>Racing</visitante>
        <resultado>
            <goles_local>4</goles_local>
            <goles_visitante>2</goles_visitante>
        </resultado>
    </partido>
</resultados>
